// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senac.GestaoReceita.WebApi.Data;

#nullable disable

namespace Senac.GestaoReceita.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230711000212_tblReceita_tbl_receitaIngrediente_Ingrediente_UnidadeMedida")]
    partial class tblReceita_tbl_receitaIngrediente_Ingrediente_UnidadeMedida
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("descricaoCidade")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("complemento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("createEmpresa")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)");

                    b.Property<int>("idUsername")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("idcidade")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("nomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("numeroEndereco")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("razaoSosial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("rua")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("updateEmpresa")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("idcidade");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeIngrediente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecoIngrediente")
                        .HasColumnType("decimal(65,30)");

                    b.Property<float>("QuantidadeUnidade")
                        .HasColumnType("float");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UnidadeMedidaId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotalReceita")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("nomeReceita")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("varchar(140)");

                    b.HasKey("Id");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.ReceitaIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdGastoVariado")
                        .HasColumnType("int");

                    b.Property<int>("IdReceita")
                        .HasColumnType("int");

                    b.Property<int>("Idingrediente")
                        .HasColumnType("int");

                    b.Property<int?>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<decimal>("qntGastoVariado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("quantidadeIngrediente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdReceita");

                    b.HasIndex("Idingrediente");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaIngredientes");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.UnidadeMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descUnidMedIngrediente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("UnidadeMedida");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.Cidade", b =>
                {
                    b.HasOne("Senac.GestaoReceita.WebApi.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.Empresa", b =>
                {
                    b.HasOne("Senac.GestaoReceita.WebApi.Models.Cidade", "cidade")
                        .WithMany()
                        .HasForeignKey("idcidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cidade");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.Ingrediente", b =>
                {
                    b.HasOne("Senac.GestaoReceita.WebApi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Senac.GestaoReceita.WebApi.Models.UnidadeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.ReceitaIngrediente", b =>
                {
                    b.HasOne("Senac.GestaoReceita.WebApi.Models.Receita", "Receita")
                        .WithMany()
                        .HasForeignKey("IdReceita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Senac.GestaoReceita.WebApi.Models.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("Idingrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Senac.GestaoReceita.WebApi.Models.Receita", null)
                        .WithMany("ReceitaIngrediente")
                        .HasForeignKey("ReceitaId");

                    b.Navigation("Ingrediente");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Senac.GestaoReceita.WebApi.Models.Receita", b =>
                {
                    b.Navigation("ReceitaIngrediente");
                });
#pragma warning restore 612, 618
        }
    }
}
